#!/bin/zsh

# DRACULA CONFIG
export XSECURELOCK_PASSWORD_PROMPT=hidden
export XSECURELOCK_SHOW_DATETIME=1
export XSECURELOCK_SHOW_USERNAME=0
export XSECURELOCK_SHOW_HOSTNAME=0
export XSECURELOCK_BACKGROUND_COLOR="#282a36"
export XSECURELOCK_AUTH_BACKGROUND_COLOR="#282a36"
export XSECURELOCK_AUTH_FOREGROUND_COLOR="#f8f8f2"
export XSECURELOCK_AUTH_WARNING_COLOR="#ff5555"

# GRUVBOX CONFIG
#export XSECURELOCK_PASSWORD_PROMPT=hidden
#export XSECURELOCK_SHOW_DATETIME=1
#export XSECURELOCK_SHOW_USERNAME=0
#export XSECURELOCK_SHOW_HOSTNAME=0
#export XSECURELOCK_BACKGROUND_COLOR="#282828"
#export XSECURELOCK_AUTH_BACKGROUND_COLOR="#3c3836"
#export XSECURELOCK_AUTH_FOREGROUND_COLOR="#fbf1c7"
#export XSECURELOCK_AUTH_WARNING_COLOR="#fb4934"

xsecurelock
