#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

~/.scripts/dual_monitor.sh
bspc monitor eDP-1 -d VI VII VIII IX X
bspc monitor HDMI-1-0 -d I II III IV V
bspc desktop -f ^1

~/.scripts/polybar/polybar_dual_monitor.sh
#feh --bg-fill "$(shuf -en1 ~/.backgrounds/random/*)"
feh --bg-fill ~/.backgrounds/flowers.png

# DRACULA COLORS
bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config single_monocle	     true
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc rule -a ranger state=floating rectangle=750x455+585+310
bspc rule -a Nemo state=floating rectangle=750x455+585+310
bspc rule -a ark state=floating
bspc rule -a feh state=floating
bspc rule -a Dconf-editor state=floating
bspc rule -a Gtk-chtheme state=floating rectangle=750x455+585+310
bspc rule -a qt5ct state=floating 
bspc rule -a qt6ct state=floating
bspc rule -a Nm-connection-editor state=floating
bspc rule -a "kitty pacmixer" state=floating rectangle=750x455+1005+54
bspc rule -a "kitty bluetui" state=floating rectangle=750x455+1020+54
bspc rule -a "kitty cmus" state=floating rectangle=750x455+585+310

picom
